README updates
RavenDevKit/ravencore pull request #6
Opened 2020-02-04 23:31 UTC by cfox

* trimmed some nonsense
* changed root dir from `insight` to `rdk`
* changed Node version from `stable` to `lts/dubnium` (10.x)
* added some new/missing config settings to examples
* changed some example settings to be more easy/permissive
* moved example config out to their own files
* tested instructions on new Ubuntu16.04/x86_64 instance

2020-02-05 16:02 UTC, cfrogjump approved these changes

2020-02-05 18:09 UTC, blondfrogs requested changes
Need to clean up these commits. 
`git` rebase -i HEAD~4` should do the trick. 
Then squash the other 3 commits, and remove the comments

2020-02-05 19:00 UTC, cfox commented
Squashed and added instructions for optionally skipping ravencoin download on installation.

2020-02-06 16:35 UTC, cfrogjump approved these changes

2020-02-06 17:22 UTC, blondfrogs approved these changes
utACK

2020-02-06 17:23 UTC, merged